# -*- coding: utf-8 -*-
"""URL Shortener

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OlE_nETjh7gLgVTeJZci82tr1KMdppV2
"""

!pip install pyshorteners

import pyshorteners

url = input("Enter URL: ")

shortener = pyshorteners.Shortener()

short_url = shortener.tinyurl.short(url)

print("Short URL:", short_url)